from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
orig=s
s=s.replace("let state=load();let currentLesson=0;let activeRole=null;let currentProfile=null;let questionsChannel=null;","let state=load();let currentLesson=0;let activeRole=null;let currentProfile=null;let questionsChannel=null;let progressChannel=null;",1)
old="async function loadRemoteQuestions(){if(!currentProfile)return;const {data,error}=await supabaseClient.from('questions').select('*').order('created_at',{ascending:true});if(error){console.error('questions load',error);return}state.questions=(data||[]).map(r=>{const idx=Number(r.module_key);return{id:r.id,employeeId:r.employee_id,moduleIndex:Number.isFinite(idx)?idx:null,moduleTitle:r.module_title||'Formación',area:Number.isFinite(idx)&&modules[idx]?modules[idx].area:'Comunicación',text:r.question_text,createdAt:fmtRemoteDate(r.created_at),updatedAt:fmtRemoteDate(r.updated_at),status:r.status,answer:r.answer_text||'',answeredAt:fmtRemoteDate(r.answered_at)}});if(currentProfile.role==='manager'){const {data:emps}=await supabaseClient.from('profiles').select('user_id,full_name,role').eq('role','employee').limit(1);if(emps&&emps[0]){state.employee.id=emps[0].user_id;state.employee.name=emps[0].full_name||state.employee.name}}else{state.employee.id=currentProfile.user_id;state.employee.name=currentProfile.full_name||state.employee.name}}"
new="async function loadRemoteQuestions(){if(!currentProfile)return;const {data,error}=await supabaseClient.from('questions').select('*').order('created_at',{ascending:true});if(error){console.error('questions load',error);return}state.questions=(data||[]).map(r=>{const idx=Number(r.module_key);return{id:r.id,employeeId:r.employee_id,moduleIndex:Number.isFinite(idx)?idx:null,moduleTitle:r.module_title||'Formación',area:Number.isFinite(idx)&&modules[idx]?modules[idx].area:'Comunicación',text:r.question_text,createdAt:fmtRemoteDate(r.created_at),updatedAt:fmtRemoteDate(r.updated_at),status:r.status,answer:r.answer_text||'',answeredAt:fmtRemoteDate(r.answered_at)}});if(currentProfile.role==='manager'){const {data:emps}=await supabaseClient.from('profiles').select('user_id,full_name,role').eq('role','employee').eq('full_name','Lucía').limit(1);if(emps&&emps[0]){state.employee.id=emps[0].user_id;state.employee.name=emps[0].full_name||state.employee.name}}else{state.employee.id=currentProfile.user_id;state.employee.name=currentProfile.full_name||state.employee.name}}"
if old not in s: raise SystemExit('loadRemoteQuestions target not found')
s=s.replace(old,new,1)
marker="function refreshRemoteUI(){if(document.querySelector('#screen-employee.active'))renderEmployee();if(document.querySelector('#screen-manager.active'))renderManager();if(document.querySelector('#screen-lesson.active'))openLesson(currentLesson)}"
insert="async function loadRemoteProgress(){if(!currentProfile)return;const employeeId=currentProfile.role==='manager'?state.employee.id:currentProfile.user_id;if(!employeeId)return;const {data,error}=await supabaseClient.from('employee_module_progress').select('*').eq('employee_id',employeeId).order('module_index',{ascending:true});if(error){console.error('progress load',error);return}state.employee.activities={};(data||[]).forEach(r=>{state.employee.activities[r.module_index]={practiced:!!r.practiced,answer:r.answer_index===null?null:r.answer_index,note:'',updatedAt:fmtRemoteDate(r.updated_at)}})}\nasync function saveRemoteProgress(i,patch){if(!currentProfile||currentProfile.role!=='employee')return;const r={...record(i),...patch};const row={employee_id:currentProfile.user_id,company_id:currentProfile.company_id,module_index:i,practiced:!!r.practiced,answer_index:r.answer===null?null:r.answer,updated_at:new Date().toISOString()};const {error}=await supabaseClient.from('employee_module_progress').upsert(row,{onConflict:'employee_id,module_index'});if(error){alert('No se pudo guardar el progreso: '+error.message);return}state.employee.activities[i]={...r,updatedAt:stamp()};refreshRemoteUI()}\nfunction startProgressRealtime(){if(progressChannel){supabaseClient.removeChannel(progressChannel);progressChannel=null}progressChannel=supabaseClient.channel('progress-pilot').on('postgres_changes',{event:'*',schema:'public',table:'employee_module_progress'},async()=>{await loadRemoteProgress();refreshRemoteUI()}).subscribe()}\n"+marker
if marker not in s: raise SystemExit('refresh marker not found')
s=s.replace(marker,insert,1)
s=s.replace("currentProfile=profile;activeRole=role;await loadRemoteQuestions();startQuestionsRealtime();show(isEmp?'screen-employee':'screen-manager')","currentProfile=profile;activeRole=role;await loadRemoteQuestions();await loadRemoteProgress();startQuestionsRealtime();startProgressRealtime();show(isEmp?'screen-employee':'screen-manager')",1)
s=s.replace("currentProfile=profile;activeRole=role;await loadRemoteQuestions();startQuestionsRealtime();show(isEmp?'screen-employee':'screen-manager');return","currentProfile=profile;activeRole=role;await loadRemoteQuestions();await loadRemoteProgress();startQuestionsRealtime();startProgressRealtime();show(isEmp?'screen-employee':'screen-manager');return",1)
s=s.replace("currentProfile=profile;activeRole=profile.role;await loadRemoteQuestions();startQuestionsRealtime();show(profile.role==='employee'?'screen-employee':'screen-manager')","currentProfile=profile;activeRole=profile.role;await loadRemoteQuestions();await loadRemoteProgress();startQuestionsRealtime();startProgressRealtime();show(profile.role==='employee'?'screen-employee':'screen-manager')",1)
oldopt="b.addEventListener('click',()=>{state.employee.activities[i]={...record(i),answer:j,updatedAt:stamp()};save();openLesson(i)})"
if oldopt not in s: raise SystemExit('option handler not found')
s=s.replace(oldopt,"b.addEventListener('click',async()=>{await saveRemoteProgress(i,{answer:j})})",1)
oldpr="$('lessonPracticed').addEventListener('change',e=>{state.employee.activities[currentLesson]={...record(currentLesson),practiced:e.target.checked,updatedAt:stamp()};save();});"
if oldpr not in s: raise SystemExit('practice handler not found')
s=s.replace(oldpr,"$('lessonPracticed').addEventListener('change',async e=>{await saveRemoteProgress(currentLesson,{practiced:e.target.checked});});",1)
if s==orig: raise SystemExit('no changes')
p.write_text(s,encoding='utf-8')
print('progress sync patched')
